root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/server.go"
bin = "./tmp/main"
entrypoint = ["./tmp/main"]
include_ext = ["go", "proto", "sh"]
stop_on_error = true
delay = 1000
log = "air.log"

[log]
time = true